pull_request_rules:
  - name: Auto merge
    conditions:
      - "#changes-requested-reviews-by=0"
      - label=st:test-and-merge
      - status-success=Jenkins
      - status-success=pretest  # github workflows
    actions:
      merge:
        method: merge
        strict: false  # strict mode and manually-triggered CIs do not get along
  - name: Notify conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
