name: "Auto Notify"

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

jobs:
  auto-notify:
    if: |
        github.repository_owner == 'cupy' &&
        github.event.label.name == 'hip'
    runs-on: ubuntu-20.04

    steps:
      - name: Find comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
            issue-number: ${{github.event.number}}
            body-includes: "<!-- Added by CuPy Auto Notify Bot -->"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
            issue-number: ${{github.event.number}}
            comment-id: ${{steps.fc.outputs.comment-id}}
            edit-mode: replace
            body: |
                <!-- Added by CuPy Auto Notify Bot -->
                cc/ @amathews-amd
